# -*- coding: utf-8 -*-
"""Copy of Applied_Tech_Project_4_Question_copy_v0.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-LIqDFwVKE_hoO3smhB84eDaNwzlJB2

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. While Loop, Data-Type Conversion and Conditional Statements

 2.  Improving the Algorithm

---

#### Getting Started:

1. Click on the following link to open the Colab file for this project.

    https://colab.research.google.com/drive/1uT0ZODSHh-jvrDectzhOj7R2Sler5zxL

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project4** format.

4. Now, write your code in the prescribed code cells.

---

### Activities

#### Activity 1: Even or Odd

Accept a number from the user and check whether it is even or odd.

For Example:

**Input**:  24

**Ouput**: Even number


Follow the steps given below to achieve the desired result:

  - **Step 1**: Ask the user to enter a number.
  
  - **Step 2**: Convert the data type of user input to integer and then store it in a variable `num`.

  - **Step 3**: Use `if` statement to determine whether the entered number is odd or even. For this, use modulo division (%). The result of a modulo division is the `remainder` of an integer division. If the number is completely divisible by 2, then print `Even number` else print `Odd number`.
"""

# Step 1: Accept a number from the user. Convert it into an integer and then store it in a variable num
num = int(input("Enter a number: "))

# Step 2: Use if condition to check whether the number is even or odd using (%) operator
if num % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")

"""---

#### Activity 2: Multiplication table

Take input from the user and display the multiplication table.

For example: if the number entered is 12 then expected output is:

  12 x 1 = 12

  12 x 2 = 24

  ....
  
  12 x 10 = 120

Follow the steps given below to achieve the desired result:

- **Step 1:** Ask the user to enter a number. Convert the data type of user input to integer and then store it in a variable `num`.

- **Step 2:** Initialize a variable `i=1` (This variable is to make sure that the `while` loop is executed only upto 10, starting from 1).

- **Step 3:** Create a `while` loop. This loop will be executed 10 times. So, the condition for `while` loop will be `i < 11`.

- **Step 4:** Multiply every value of the `i` variable with the value of the `num` variable and store in the `multiply` variable.

- **Step 5**: Print the result stored in the `multiply` variable using the `print()` function and increment the value of `i` by 1 inside the `while` loop. The execution stops once the condition for `while` loop becomes invalid.
"""

# Step 1: Get the user input
num = int(input("Enter a number: "))

# Step 2: Initialize variable 'i' with value '1'
i = 1

# Step 3: Execute a 'while' loop 10 times
while i <= 10:

  # Step 4: Multiply the 'num' variable with 'i' variable and store in 'multiply' variable.
  multiply = num * i

  # Print the result stored in the `multiply` variable
  print(f"{num} x {i} = {multiply}")

  # Increment the value of 'i' by 1
  i += 1

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project4**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project4** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""